platform :ios, '12.0'
use_frameworks!

target 'RxCacheMap_Example' do
  pod 'RxCacheMap', :path => '../'
  pod 'RxSwift', '~> 6.0'
  pod 'RxCocoa', '~> 6.0'
  target 'RxCacheMap_Tests' do
    inherit! :search_paths
    pod 'RxBlocking', '~> 6.0'
    pod 'RxTest', '~> 6.0'
  end
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
  end
 end
end
